__packages:
  - autoconf
  - gcc 
  - make 
  - pkg-config
  - libpam0g-dev
  - libcairo2-dev
  - libfontconfig1-dev
  - libxcb-composite0-dev
  - libev-dev
  - libx11-xcb-dev
  - libxcb-xkb-dev
  - libxcb-xinerama0-dev
  - libxcb-randr0-dev
  - libxcb-image0-dev
  - libxcb-util-dev
  - libxcb-xrm-dev
  - libxkbcommon-dev
  - libxkbcommon-x11-dev
  - libjpeg-dev
  - x11-xserver-utils
  - imagemagick
  - bspwm
  - sxhkd
  - dunst
  - picom
  - polybar
  - rofi
