- include_vars: "{{ ansible_facts['distribution'] | lower }}.yml"

- name: install desktop engine packages
  become: yes
  ansible.builtin.package:
    name: "{{ __packages | list }}"
    state: present

- name: install betterlockscreen on ubuntu
  block:
    - name: Clone i3lock-color
      ansible.builtin.git:
        repo: "https://github.com/Raymo111/i3lock-color.git"
        version: "2.13.c.4"
        clone: yes
        dest: "{{ ansible_env.HOME }}/workspace/i3lock-color"
    - name: Build i3lock-color on ubuntu
      ansible.builtin.command: "./build.sh"
      args:
        chdir: "{{ ansible_env.HOME }}/workspace/i3lock-color" 
    - name: Install i3lock-color on ubuntu
      become: yes
      ansible.builtin.command: "make install"
      args:
        chdir: "{{ ansible_env.HOME }}/workspace/i3lock-color/build" 
    - name: fetch betterlockscreen
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/next/betterlockscreen"
        dest: "{{ ansible_env.HOME }}/betterlockscreen"
        mode: "+x"
    - name: install betterlockscreen
      become: yes
      ansible.builtin.command: "cp {{ ansible_env.HOME }}/betterlockscreen /usr/bin/betterlockscreen"
    - name: remove betterlockscreen download
      ansible.builtin.command: "rm {{ ansible_env.HOME }}/betterlockscreen"
      args:
        warn: false
  when: ansible_distribution == "Ubuntu"
- name: install betterlockscreen on Archlinux
  # become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: betterlockscreen
    use: paru
    state: present
  when: ansible_distribution == "Archlinux"
